const { TERM_WIDTH } = require('../status');

const RATE_LIMIT_MS = 3000;
const SPAM_THRESHOLD = 5;
const SPAM_COOLDOWN_MS = 30000;
const EVOLUTION_IDLE_MS = 15 * 60 * 1000;
const DEDUP_TTL_MS = 5 * 60 * 1000;
const DEDUP_MAX_SIZE = 2000;
const TEXT_BUFFER_GAP_MS = 1500;
const TEXT_BUFFER_MAX_PARTS = 12;
const TEXT_BUFFER_MAX_CHARS = 50000;
const TEXT_BUFFER_THRESHOLD = 4000;
const MEDIA_GROUP_DELAY_MS = 500;
const MAX_MEDIA_SIZE = 50 * 1024 * 1024;
const TERM_SEP = '━'.repeat(TERM_WIDTH);

module.exports = {
  RATE_LIMIT_MS,
  SPAM_THRESHOLD,
  SPAM_COOLDOWN_MS,
  EVOLUTION_IDLE_MS,
  DEDUP_TTL_MS,
  DEDUP_MAX_SIZE,
  TEXT_BUFFER_GAP_MS,
  TEXT_BUFFER_MAX_PARTS,
  TEXT_BUFFER_MAX_CHARS,
  TEXT_BUFFER_THRESHOLD,
  MEDIA_GROUP_DELAY_MS,
  MAX_MEDIA_SIZE,
  TERM_SEP,
};
